version: "3.9"

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./src:/home/app/src          # live code updates
      - ./.streamlit:/home/app/.streamlit  # live theme/config updates
